#ifndef BUS_FRAME_WRITER_STATUS_H
#define	BUS_FRAME_WRITER_STATUS_H

typedef enum {
    BUS_FRAME_WRITER_OPERATION_NONE = 0,
    BUS_FRAME_WRITER_OPERATION_OK,
    BUS_FRAME_WRITER_ERROR_WRITING,
} eBusFrameWriterOperationStatus;

#endif	/* BUS_FRAME_WRITER_STATUS_H */