#ifndef BUS_FRAME_HANDLER_STATUS_H
#define	BUS_FRAME_HANDLER_STATUS_H

typedef enum {
    BUS_HANDLER_OPERATION_NONE = 0,
    BUS_HANDLER_OPERATION_OK,
    BUS_HANDLER_CANT_WRITE,
} eBusHandlerOperationStatus;

#endif	/* BUS_FRAME_HANDLER_STATUS_H */

